server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ysx
    data-username: root
    data-password: root

#设置xml文件生成的路径
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ysx.demo.model
  configuration.cache-enabled: false
#  关闭驼峰映射为下划线
  configuration.map-underscore-to-camel-case: false
  global-config.db-config.db-type: mysql
#  configuration.jdbc-type-for-null: null

logging:
  config: classpath:logback-spring.xml

#数据源的配置
db:
  url: jdbc:mysql://localhost:3306/ysx
  username: root
  password: root
